### ISSUE TITLE
IsInvalidTime gives wrong result when running on Linux

### ISSUE THREAD

**Issue by mohoch1** [mj1856/TimeZoneConverter#83] opened 2020-12-24 12:41 UTC
Hi.
Thanks a lot for this very helpful library.

I am using version 3.3.0 in a .NET Core application running in Docker on a Linux machine.

I was checking for invalid hours (in DST transition) and got a wrong result when running on Linux, but correct results when running the same code on a Windows machine.

An example is "2010-05-02" in "Morocco Standard Time"  - which is an Invalid hour, but was described as Valid on Linux.

This is the code I used.
```
public static bool IsTimeValid(DateTime dateTime, string timeZoneId)
{	var locationTimeZone = TimeZoneConverter.TZConvert.GetTimeZoneInfo(timeZoneId);
	var isInvalid = locationTimeZone.IsInvalidTime(dateTime);
	return !isInvalid;
}
```

And then run it with 
`IsTimeValid(new DateTime(2010,5,2), "Morocco Standard Time")`

Thanks

**Comment by mj1856** [comment] 2020-12-25 03:58
Do you have valid tzdata loaded on your Linux image?  Is the image based on Alpine linux by chance?
See https://github.com/mj1856/TimeZoneConverter#note-on-os-data-dependencies

**Comment by mohoch1** [comment] 2020-12-27 10:09
We do have tzdata, I guess, since we do get correct results for other time zones.
for example `IsTimeValid(new DateTime(2020,3,8), "Cuba Standard Time")` gave the  correct result of "false"

It seems that Morocco is just configured wrong somehow.
I will look if other time zones have this issue

**Comment by mj1856** [comment] 2020-12-27 17:49
Keep in mind that TimeZoneConverter simply translates the Windows ID to an IANA ID, in this case `Africa/Casablanca`.  The rest is done by the `TimeZoneInfo` class in .NET itself.

**Comment by mohoch1** [comment] 2020-12-30 09:07
from what I found, the mapped adjustment rules are not accurate.
This is a JSON of the adjustment rule mapped from the tzdata on the **Linux**:

> {
>       "DateStart":"2010-05-02T00:00:00Z",
>       "DateEnd":"2010-08-07T22:59:59.9999999Z",
>       "**DaylightDelta":"00:00:00",**
>       "DaylightTransitionStart":{
>          "TimeOfDay":"0001-01-01T00:00:00.002",
>          "Month":1,
>          "Week":1,
>          "Day":1,
>          "DayOfWeek":0,
>          "IsFixedDateRule":true
>       },
>       "DaylightTransitionEnd":{
>          "TimeOfDay":"0001-01-01T00:00:00",
>          "Month":0,
>          "Week":0,
>          "Day":0,
>          "DayOfWeek":0,
>          "IsFixedDateRule":false
>       },
>       "BaseUtcOffsetDelta":"00:00:00",
>       "NoDaylightTransitions":true
>    },
>    {
>       "DateStart":"2010-08-07T23:00:00Z",
>       "DateEnd":"2011-04-02T23:59:59.9999999Z",
>       **"DaylightDelta":"00:00:00",**
>       "DaylightTransitionStart":{
>          "TimeOfDay":"0001-01-01T00:00:00",
>          "Month":0,
>          "Week":0,
>          "Day":0,
>          "DayOfWeek":0,
>          "IsFixedDateRule":false
>       },
>       "DaylightTransitionEnd":{
>          "TimeOfDay":"0001-01-01T00:00:00",
>          "Month":0,
>          "Week":0,
>          "Day":0,
>          "DayOfWeek":0,
>          "IsFixedDateRule":false
>       },
>       "BaseUtcOffsetDelta":"-01:00:00",
>       "NoDaylightTransitions":true
>    }
> 

And this one is from **Windows:**

>  {
>       "DateStart":"2010-01-01T00:00:00",
>       "DateEnd":"2010-12-31T00:00:00",
>       **"DaylightDelta":"01:00:00",**
>       "DaylightTransitionStart":{
>          "TimeOfDay":"0001-01-01T23:59:59.999",
>          "Month":5,
>          "Week":1,
>          "Day":1,
>          "DayOfWeek":6,
>          "IsFixedDateRule":false
>       },
>       "DaylightTransitionEnd":{
>          "TimeOfDay":"0001-01-01T23:59:59.999",
>          "Month":8,
>          "Week":1,
>          "Day":1,
>          "DayOfWeek":6,
>          "IsFixedDateRule":false
>       },
>       "BaseUtcOffsetDelta":"00:00:00",
>       "NoDaylightTransitions":false
>    }
> 

The DaylightDelta is the part that is used in the .NET code to determine if an hour is valid or not, and this case, this property is left as zero.

**Comment by mj1856** [comment] 2020-12-30 19:32
Yes, I see.  

Since TimeZoneConverter is correctly loading `"Africa/Casablanca"` on Linux when given `"Morocco Standard Time"`, the issue is in the .NET Runtime, not here.  So I will close this issue.

I think you might be experiencing the issue described in https://github.com/dotnet/runtime/issues/20626.  Please continue there so the .NET team can assess.  Thanks.

**Closed by mj1856** 2020-12-30 19:32 UTC

**Comment by tarekgh** [comment] 2020-12-30 20:23
@mohoch1 which Linux distro you are using? can you try to dump the TZ data on this Linux disto for Morocco? (don't use donnet for that, try to use something like https://man7.org/linux/man-pages/man8/zdump.8.html)

@mj1856 we know we have issue when reporting the adjustment rules but not necessary the TZ adjustment rule data we internally using is not correct. You know we always do some conversion from the internal data representation of the adjustment rules before we report it to the caller.
